PRAGMA defer_foreign_keys=TRUE;
CREATE TABLE IF NOT EXISTS "aircraft_seen" (
  hex           TEXT NOT NULL,
  registration  TEXT,
  type          TEXT,
  flight        TEXT,
  seen_date     TEXT NOT NULL, operator TEXT, origin TEXT, destination TEXT, enriched INTEGER DEFAULT 0, confidence TEXT, owner TEXT, airline TEXT,
  PRIMARY KEY (hex, seen_date)
);
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('ab0ffd','N8114F','P28A','N8114F','2026-06-06',NULL,NULL,'KMLI',1,'high','FLYING COUNTRY CLUB INC',NULL);
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('a915cf','N685AE','E145','PDT5795','2026-06-06','PDT','KMLI','KCLT',1,'high','American Eagle','ENY');
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('a32f82','N304PQ','CRJ9','EDV4958','2026-06-06','EDV','KMLI','KATL',1,'high','Delta Connection','EDV');
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('ac42bf','N8898L','B38M',NULL,'2026-06-06',NULL,NULL,NULL,2,'low','Southwest Airlines','SWA');
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('a37833','N32204','P28A','N32204','2026-06-06',NULL,'KMLI','KMLI',1,'high','FLYING COUNTRY CLUB INC',NULL);
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('accb22','N923US','A321','AAL751','2026-06-06','AAL','KCLT','KSEA',1,'medium','American Airlines','AAL');
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('a0b803','N14529','A21N',NULL,'2026-06-06',NULL,NULL,NULL,3,'none',NULL,NULL);
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('a53e35','N437MC','CL60',NULL,'2026-06-06',NULL,NULL,NULL,2,'low','Cirrus Aviation','CL64');
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('aa11c9','N748RR','E170','ENY3445','2026-06-06','ENY','KMLI','KORD',1,'high',NULL,NULL);
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('ab2048',NULL,NULL,NULL,'2026-06-06',NULL,NULL,NULL,3,'none',NULL,NULL);
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('aa781f','N774CK','B77L',NULL,'2026-06-06',NULL,NULL,NULL,2,'low','Kalitta Air','CKS');
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('ad6ec6','N965AN','B738',NULL,'2026-06-06',NULL,NULL,NULL,2,'low','American Airlines','AAL');
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('a84200','N631FR','A21N',NULL,'2026-06-06',NULL,NULL,NULL,2,'low','Bank of Utah Trustee','C441');
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('a69fd7','N526GJ','CRJ7','GJS4542','2026-06-06','GJS','KMLI','KORD',1,'high','United Express','GJS');
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('a01ca5','N106SY','E75L',NULL,'2026-06-06',NULL,NULL,NULL,2,'low','United Express','SKW');
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('a227a7','N238QS','CL60',NULL,'2026-06-06',NULL,NULL,NULL,2,'low','NetJets','EJA');
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('a28904','N26215','B738',NULL,'2026-06-06',NULL,NULL,NULL,2,'low','United Airlines','UAL');
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('a09a90','N138SY','E75L','SKW5392','2026-06-06','SKW','KORD','KOKC',1,'medium','United Express','SKW');
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('aa72b1','N772YX','E75L',NULL,'2026-06-06',NULL,NULL,NULL,3,'none',NULL,NULL);
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('aa998e','N782SK','CRJ7','SKW4692','2026-06-06','SKW','KMLI','KDEN',1,'high','United Express','SKW');
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('aa0300','N744SK','CRJ7',NULL,'2026-06-06',NULL,NULL,NULL,2,'low','American Eagle','SKW');
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('ac5b20','N8956Q','B38M',NULL,'2026-06-06',NULL,NULL,NULL,3,'none',NULL,NULL);
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('a7f096','N610UX','E75L',NULL,'2026-06-06',NULL,NULL,NULL,2,'low','United Express','SKW');
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('aaef89','N8031M','A319','AAL1039','2026-06-06','AAL','KCID','KCLT',1,'medium','American Airlines','AAL');
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('a05671','N12028','A319',NULL,'2026-06-06',NULL,NULL,NULL,2,'low','American Airlines','AAL');
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('a34ae0','N311DN','A321',NULL,'2026-06-06',NULL,NULL,NULL,2,'low','Delta Air Lines','DAL');
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('aa4200','N760EV','CRJ7',NULL,'2026-06-06',NULL,NULL,NULL,2,'low','American Eagle','SKW');
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('a32422','N301MF','EC35','N301MF','2026-06-06',NULL,NULL,NULL,1,'medium','Quad City Helicopter EMS','EC35');
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('ad4eb5','N957AN','B738',NULL,'2026-06-06',NULL,NULL,NULL,2,'low','American Airlines','AAL');
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('a35854','N3142J','BCS3',NULL,'2026-06-07',NULL,NULL,NULL,2,'low','JetBlue Airways','JBU');
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('a25c6e','N251NN','E75L','ENY3534','2026-06-07','ENY','KMLI','KDFW',1,'high','American Eagle','ENY');
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('a0e250','N156UW','A321','AAL2786','2026-06-07','AAL','KORD','KPHX',1,'medium','American Airlines','AAL');
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('a4c6af','N407AN','A21N',NULL,'2026-06-07',NULL,NULL,NULL,2,'low','American Airlines','AAL');
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('a332fe','N305MF','EC35','N305MF','2026-06-07',NULL,NULL,NULL,1,'medium','Quad City Helicopter EMS','EC35');
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('a65b76','N509AY','A321',NULL,'2026-06-07',NULL,NULL,NULL,2,'low','American Airlines','AAL');
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('a46310','N382DN','A321',NULL,'2026-06-07',NULL,NULL,NULL,2,'low','Delta Air Lines','DAL');
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('ac6a65','N8999Q','B38M',NULL,'2026-06-07',NULL,NULL,NULL,3,'none',NULL,NULL);
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('a385ee','N326PQ','CRJ9','EDV4937','2026-06-07','EDV','KMLI','KATL',1,'high','Delta Connection','EDV');
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('a6898d','N520GJ','CRJ7',NULL,'2026-06-07',NULL,NULL,NULL,3,'none',NULL,NULL);
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('a06aba','N126HQ','E75L',NULL,'2026-06-07',NULL,NULL,NULL,3,'none',NULL,NULL);
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('a93229','N692AE','E145',NULL,'2026-06-07',NULL,NULL,NULL,3,'none',NULL,NULL);
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('a788d3','N585DN','A21N',NULL,'2026-06-07',NULL,NULL,NULL,3,'none',NULL,NULL);
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('ad7e2e','N969GC','E55P',NULL,'2026-06-07',NULL,NULL,NULL,3,'none',NULL,NULL);
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('a44197','N3732J','B738','DAL2142','2026-06-07','DAL','KCMH','KSLC',1,'medium','Delta Air Lines','DAL');
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('ab9413','N845SY','B738',NULL,'2026-06-07',NULL,NULL,NULL,3,'none',NULL,NULL);
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('a73a1c','N565GJ','CRJ7',NULL,'2026-06-07',NULL,NULL,NULL,3,'none',NULL,NULL);
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('a7338c','N563RF','SR22','N563RF','2026-06-07',NULL,'KTVC','KMLI',1,'high','HJC AIRCRAFT LLC',NULL);
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('ad0022','N937EV','CRJ2','SKW4723','2026-06-07','SKW','KMLI','KORD',1,'high','United Express','SKW');
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('a7de93','N606LR','CRJ9','EDV4644','2026-06-07','EDV','KMLI','KATL',1,'high','Delta Connection','EDV');
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('a33325','N305NV','A319',NULL,'2026-06-07',NULL,NULL,NULL,3,'none',NULL,NULL);
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('a0a446','N140SF','EC45','N140SF','2026-06-07',NULL,NULL,NULL,2,'low','OSF Aviation','EC45');
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('a4ad49','N400GT','C210','N400GT','2026-06-07',NULL,'KCWI','KCPS',1,'medium','ARNOLD FINANCIAL SERVICES INC',NULL);
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('a9c082','N7274S','C82S','N7274S','2026-06-07',NULL,'KMLI','KDET',1,'high','HAMAKER MICHAEL C',NULL);
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('a81efa','N622PK','TBM9','N622PK','2026-06-07',NULL,'KMLI','KHPN',1,'high','Rigidworks LLC','TBM9');
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('a690fb','N522GJ','CRJ7','GJS4524','2026-06-07','GJS','KMLI','KORD',1,'high','United Express','GJS');
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('a980d4','N711LX','C56X',NULL,'2026-06-07',NULL,NULL,NULL,3,'none',NULL,NULL);
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('a2cf3b','N280NV','A320',NULL,'2026-06-07',NULL,NULL,NULL,2,'low','Allegiant Air','AAY');
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('a666df','N511TR','S22T',NULL,'2026-06-07',NULL,NULL,NULL,3,'none',NULL,NULL);
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('adb7ee','N983SW','CRJ2','SKW4806','2026-06-07','SKW','KORD','KMLI',1,'high','United Express','SKW');
INSERT INTO "aircraft_seen" ("hex","registration","type","flight","seen_date","operator","origin","destination","enriched","confidence","owner","airline") VALUES('a3be8f','N340NW','A320','DAL1543','2026-06-07','DAL','KDTW','KDFW',1,'medium','Delta Air Lines','DAL');
CREATE INDEX idx_seen_date ON aircraft_seen(seen_date);
CREATE INDEX idx_type ON aircraft_seen(type);
CREATE INDEX idx_registration ON aircraft_seen(registration);
